import json


products = [
    {
        "id": "The-Life-of-a-Meatball",
        "image": "https://unlim8ted.com/images/products/films/The%20Life%20of%20a%20Meatball.jpg",
        "additional_images": [
            "https://unlim8ted.com/images/products/films/The%20Life%20of%20a%20Meatball1.jpg"
        ],
        "video": "https://unlim8ted.com/videos/products/films/the life of a meatball/The Life of a Meatball Trailer.mov",
        "additional_videos": [
            "https://unlim8ted.com/videos/products/films/the life of a meatball/The Life of a Meatball Transition.mov"
        ],
        "name": "The Life of a Meatball",
        "description": "Deep within the Tasmanian Jungles lie meatball factories. These factories produce meatballs, although something quite special can happen as shown in this captivating documentary.",
        "price": 0.0,
        "link": "https://youtu.be/FiDwWp7ZteE",
    },
    {
        "id": "ChatApp",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "ChatApp",
        "description": "Lets you chat with your friends with entertaining visuals and easy to use UI's. Python • 0 • 0 • 0 • 0 • Updated Mar 8, 2024",
        "price": 0,
        "type": "Entertainment",
        "link": "https://github.com/Unlim8ted-Studio-Productions/ChatApp",
    },
    {
        "id": "ChessVR",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "ChessVR",
        "description": "ChessVR repository. No further description available.",
        "price": 0,
        "type": "Entertainment",
        "link": "https://github.com/Unlim8ted-Studio-Productions/ChessVR",
    },
    {
        "id": "Download-Any-Youtube-Video",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "Download-Any-Youtube-Video",
        "description": "Python script to download any YouTube video, either for watching it later, or using it in a project. Python • 0 • 1 • 0 • 0 • Updated Jun 9, 2024",
        "price": 0,
        "type": "Entertainment",
        "link": "https://github.com/Unlim8ted-Studio-Productions/Download-Any-Youtube-Video",
    },
    {
        "id": "Easy_pygame_UI-Maker",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "Easy_pygame_UI-Maker",
        "description": "Pygame UI Designer for creating and customizing UI elements and menues. HTML • 0 • 0 • 0 • 0 • Updated Mar 21, 2024",
        "price": 0,
        "type": "Productivity",
        "link": "https://github.com/Unlim8ted-Studio-Productions/Easy_pygame_UI-Maker",
    },
    {
        "id": "Face-Stuff",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "Face-Stuff",
        "description": "Various face experiments using AI technology to apply various fun effects to your face and even controll your computer with your hands. No further description available. Python • 0 • 0 • 0 • 0 • Updated May 18, 2024",
        "price": 0,
        "type": "Entertainment",
        "link": "https://github.com/Unlim8ted-Studio-Productions/Face-Stuff",
    },
    {
        "id": "FTL-ChooseYourSide",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "FTL-ChooseYourSide",
        "description": "An FTL mod made using the FTL-Node-Based-Modding tool. No further description available. Python • 0 • 0 • 0 • 0 • Updated Feb 5, 2024",
        "price": 0,
        "type": "Entertainment",
        "link": "https://github.com/Unlim8ted-Studio-Productions/FTL-ChooseYourSide",
    },
    {
        "id": "FTL-Node-Based-Modding",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "FTL-Node-Based-Modding",
        "description": "A tool to create FTL mods through a visual node based system, dramatically speeding up the proccess of writing FTL XML code. Python • 0 • 0 • 0 • 0 • Updated Feb 25, 2024",
        "price": 0,
        "type": "Productivity",
        "link": "https://github.com/Unlim8ted-Studio-Productions/FTL-Node-Based-Modding",
    },
    {
        "id": "Kindel-E-ink-games",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "Kindel-E-ink-games",
        "description": "Kindel-E-ink-games repository. No further description available. JavaScript • 0 • 0 • 0 • 0 • Updated Mar 3, 2024",
        "price": 0,
        "type": "Entertainment",
        "link": "https://github.com/Unlim8ted-Studio-Productions/Kindel-E-ink-games",
    },
    {
        "id": "Multiplayer-Physics-Simulator",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "Multiplayer-Physics-Simulator",
        "description": "Multiplayer-Physics-Simulator repository. No further description available. Python • 0 • 0 • 0 • 0 • Updated Apr 16, 2024",
        "price": 0,
        "type": "Entertainment",
        "link": "https://github.com/Unlim8ted-Studio-Productions/Multiplayer-Physics-Simulator",
    },
    {
        "id": "Music-AI-Gen",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "Music-AI-Gen",
        "description": "Music-AI-Gen repository. No further description available. Python • 0 • 0 • 0 • 0 • Updated Feb 14, 2024",
        "price": 0,
        "type": "Entertainment",
        "link": "https://github.com/Unlim8ted-Studio-Productions/Music-AI-Gen",
    },
    {
        "id": "Organisms_Sim",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "Organisms_Sim",
        "description": "Various simulations showcasing evolution, natural selection, and nural networks.",
        "price": 0,
        "type": "Entertainment",
        "link": "https://github.com/Unlim8ted-Studio-Productions/Organisms_Sim",
    },
    {
        "id": "paint-app-v5.9",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "paint-app-v5.9",
        "description": "A fun painting app with cool effects.",
        "price": 0,
        "type": "Entertainment",
        "link": "https://github.com/Unlim8ted-Studio-Productions/paint-app-v5.9",
    },
    {
        "id": "Square-Pixels",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "Square-Pixels",
        "description": "Pixelated sandbox adventure game with exploration, crafting, and multiplayer.",
        "price": 0,
        "type": "Entertainment",
        "link": "square-pixels",
    },
    {
        "id": "turbo-octo-funicular",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [None, None],
        "name": "turbo-octo-funicular",
        "description": "turbo-octo-funicular repository. No further description available.",
        "price": 0,
        "type": "Entertainment",
        "link": "https://github.com/Unlim8ted-Studio-Productions/turbo-octo-funicular",
    },
    {
        "id": "wrighting",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "wrighting",
        "description": "wrighting repository. No further description available. HTML • 0 • 0 • 0 • 0 • Updated Mar 3, 2024",
        "price": 0,
        "type": "Productivity",
        "link": "https://github.com/Unlim8ted-Studio-Productions/wrighting",
    },
    {
        "id": "life",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "life",
        "description": "card game",
        "price": 0,
        "type": "Entertainment",
    },
    {
        "id": "PuzzleSquare1",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "Puzzle Square 1",
        "description": "Solve a tricky mystery.",
        "price": 0,
        "type": "Entertainment",
    },
    {
        "id": "PuzzleSquare2",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "Puzzle Square 2",
        "description": "Solve a tricky mystery.",
        "price": 0,
        "type": "Entertainment",
    },
    {
        "id": "theglitch",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "The Glitch",
        "description": "In progress...",
        "price": 0,
        "type": "Entertainment",
    },
    {
        "id": "theglitchbook",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "The Glitch (the book)",
        "description": "In progress...",
        "price": 0,
        "type": "Entertainment",
    },
    {
        "id": "theglitchscreenplay",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "The Glitch (the screen play)",
        "description": "The screen play for the short film 'The Glitch'.",
        "price": 0,
        "type": "Entertainment",
        "link": "https://docs.google.com/document/d/1SYcF4x2AdHc1DwZstHEIL2uV-Fe5pHN3iR-lZnyupso/edit?usp=sharing",
    },
    {
        "id": "Copy-Keyframes-to-Selected-Blender-Addon",
        "image": None,
        "additional_images": [],
        "video": None,
        "additional_videos": [],
        "name": "Copy Keyframes to Selected Blender Addon",
        "description": "A Blender Addon that makes it easy to copy keyframes to multiple objects from in the N-Panel",
        "price": 0,
        "type": "Productivity",
        "link": "https://github.com/Unlim8ted-Studio-Productions/Blender-Copy-Keyframe-Addon",
    },
]


product_page_links = [
    {
        "name": "The Life of a Meatball",
        "link": "https://unlim8ted.com/products#The-Life-of-a-Meatball",
    },
    {"name": "The Glitch", "link": "https://unlim8ted.com/products#theglitch"},
    {
        "name": "The Life of a Meatball Puzzle",
        "link": "https://unlim8ted.com/squareproduct#the-life-of-a-meatball-jigsaw-puzzle/20",
    },
    {"name": "Puzzle Square 1", "link": "https://unlim8ted.com/puzzle-squares"},
    {"name": "Puzzle Square 2", "link": "https://unlim8ted.com/puzzle-squares"},
    {"name": "life", "link": "https://unlim8ted.com/products#life"},
    {
        "name": "The Glitch (book)",
        "link": "https://unlim8ted.com/products#theglitchbook",
    },
    {
        "name": "The Glitch (screen play)",
        "link": "https://unlim8ted.com/products#theglitchscreenplay",
    },
    {"name": "Alien", "link": "https://unlim8ted.com/products"},
    {"name": "The pool world war.", "link": "https://unlim8ted.com/products"},
    {"name": "The Crystal's Conflict", "link": "https://unlim8ted.com/products"},
    {"name": "The Hidden Magic School", "link": "https://unlim8ted.com/products"},
    {"name": "Holes in space and time.", "link": "https://unlim8ted.com/products"},
    {"name": "Stranded", "link": "https://unlim8ted.com/products"},
    {"name": "Ancient", "link": "https://unlim8ted.com/products"},
    {"name": "Square Pixels", "link": "https://unlim8ted.com/products#Square-Pixels"},
    {
        "name": "Download Any Youtube Video",
        "link": "https://unlim8ted.com/products#Download-Any-Youtube-Video",
    },
    {"name": "Face Stuff", "link": "https://unlim8ted.com/products#Face-Stuff"},
    {
        "name": "Multiplayer Physics Simulator",
        "link": "https://unlim8ted.com/products#Multiplayer-Physics-Simulator",
    },
    {
        "name": "Easy pygame UI Creator",
        "link": "https://unlim8ted.com/products#Easy-Pygame-UI-Creator",
    },
    {"name": "ChatApp", "link": "https://unlim8ted.com/products#ChatApp"},
    {"name": "Organisms Sim", "link": "https://unlim8ted.com/products#Organisms_Sim"},
    {
        "name": "FTL Node Based Modding",
        "link": "https://unlim8ted.com/products#FTL-Node-Based-Modding",
    },
    {
        "name": "FTL ChooseYourSide",
        "link": "https://unlim8ted.com/products#FTL-ChooseYourSide",
    },
    {"name": "wrighting", "link": "https://unlim8ted.com/products#wrighting"},
    {"name": "Music AI Gen", "link": "https://unlim8ted.com/products#Music-AI-Gen"},
    {"name": "ChessVR", "link": "https://unlim8ted.com/products#ChessVR"},
    {
        "name": "Kindel E-ink games",
        "link": "https://unlim8ted.com/products#Kindel-E-ink-games",
    },
    {
        "name": "turbo-octo-funicular",
        "link": "https://unlim8ted.com/products#turbo-octo-funicular",
    },
    {"name": "Unicornia", "link": "https://unlim8ted.com/products#unicornia"},
    {"name": "Confuzzled", "link": "https://unlim8ted.com/products#confuzzled"},
    {
        "name": "Copy Keyframes to Selected (Blender Addon)",
        "link": "https://unlim8ted.com/products#Copy-Keyframes-to-Selected-Blender-Addon",
    },
]

# Convert list of links to a dictionary for faster lookup

links_dict = {item["name"]: item["link"] for item in product_page_links}


# Replace links in products list
for product in products:
    if product["name"] in links_dict:
        product["link"] = links_dict[product["name"]]


# Save updated products as JSON

output_file = "output.json"
with open(output_file, "w") as f:
    json.dump(products, f, indent=4)


output_file
